# Generated by Django 6.0.3 on 2026-04-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maquina', models.AutoField(primary_key=True, serialize=False)),
                ('nome_maquina', models.CharField(max_length=100, unique=True, verbose_name='Nome da Maquina')),
                ('valor_limite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limite de gasto')),
            ],
        ),
    ]
