# Generated by Django 6.0.3 on 2026-04-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maquina',
            new_name='Maquinas_Model',
        ),
    ]
