# Generated by Django 6.0.3 on 2026-04-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_rename_maquina_maquinas_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinas_model',
            name='imagem_maquina',
            field=models.ImageField(blank=True, null=True, upload_to='maquininhas'),
        ),
    ]
