# Generated by Django 6.0.3 on 2026-04-09 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0003_maquinas_model_imagem_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinas_model',
            name='dia_vencimento',
            field=models.PositiveIntegerField(default=1, help_text='Escolha um dia entre 1 e 31 para o fechamento do ciclo.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
