# Generated by Django 6.0.3 on 2026-04-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0004_maquinas_model_dia_vencimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquinas_model',
            options={'verbose_name': 'Máquininha', 'verbose_name_plural': 'Máquininhas'},
        ),
    ]
