# Generated by Django 6.0.3 on 2026-05-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0005_alter_maquinas_model_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinas_model',
            name='valor_limite_anual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Limite anual'),
        ),
    ]
