# Generated by Django 6.0.3 on 2026-05-02 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0006_maquinas_model_valor_limite_anual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinas_model',
            name='valor_limite',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(100000)], verbose_name='Limite de gasto'),
        ),
        migrations.AlterField(
            model_name='maquinas_model',
            name='valor_limite_anual',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)], verbose_name='Limite anual'),
        ),
    ]
