# Generated by Django 6.0.3 on 2026-04-09 00:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinas', '0004_maquinas_model_dia_vencimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas_Model',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=6)),
                ('produto_vendido', models.CharField(blank=True, max_length=200, null=True)),
                ('data_venda', models.DateField(default=django.utils.timezone.now)),
                ('maquina_to_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='maquinas.maquinas_model')),
            ],
        ),
    ]
