# Generated by Django 6.0.3 on 2026-04-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas_model',
            name='comprovante',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
