# Generated by Django 6.0.3 on 2026-04-22 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0002_vendas_model_comprovante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas_model',
            name='produto_vendido',
        ),
    ]
