# Generated by Django 6.0.3 on 2026-04-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0003_remove_vendas_model_produto_vendido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas_model',
            options={'verbose_name': 'Lançamento', 'verbose_name_plural': 'Lançamentos'},
        ),
    ]
