# Generated by Django 6.0.3 on 2026-05-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0004_alter_vendas_model_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas_model',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
